[package]
name = "TTKServer"
version = "0.9.1"
edition = "2021"
default-run = "TTKServer"

[lib]
name = "ttk_server"
path = "src/lib.rs"

[[bin]]
name = "TTKServer"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
rustls = { version = "0.23", features = ["ring"] }
aws-nitro-enclaves-nsm-api = { version = "0.4", optional = true }
sha2 = "0.10"
base64 = "0.21"
ciborium = "0.2"
log = "0.4"
env_logger = "0.11"
rustls-pki-types = "1"
rcgen = "0.13"
quinn = "0.11"
axum = "0.8.9"
h3 = "0.0.7"        # The core HTTP/3 state machine
h3-quinn = "0.0.9"
time = "0.3.36"
rustls-pemfile = "2.2.0"
der-parser = "10.0.0"
x509-parser = "0.18.1"
serde = { version = "1.0.228", features = ["derive"] }  # The adapter bridging Quinn's QUIC API to h3's Transport trait
aws-nitro-enclaves-cose = "0.5"
[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = "0.3"

[features]
default = ["nitro", "mock"]

nitro = ["dep:aws-nitro-enclaves-nsm-api"]
mock = ["dep:aws-nitro-enclaves-nsm-api"]
sev-snp = []
tdx = []
