[book]
title = "TTKServer"
authors = ["Nikos Zikos"]
language = "en"
src = "src"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
